server:
  port: 8081

spring:
  application:
    name: customer-service

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 10

custom:
  message: "Customer Service - Config Padrão"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  
  api-docs:
    path: /v3/api-docs